import Head from "next/head";
import Header from "@/components/header";

import objects_json from "@/json/objects.json";
import verbs_json from "@/json/verbs.json";
import sectors_json from "@/json/sectors.json";
import useRoulette from "@/hooks/useRoulette";
import Roulette from "@/components/Roulette";
import { cyan, orange, magenta } from "@ant-design/colors";

export default function Home() {
  const { result: sector, wordList: sectors } = useRoulette({
    jsonText: sectors_json,
    jsonType: 1,
  });
  const { result: verb, wordList: verbs } = useRoulette({
    jsonText: verbs_json,
    jsonType: 3,
  });
  const { result: object, wordList: objects } = useRoulette({
    jsonText: objects_json,
    jsonType: 3,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="roulette-wraper">
        <Roulette wordList={sectors} title="sector" color={cyan[7]} />
        <Roulette wordList={verbs} title="verb" color={orange[7]} />
        <Roulette wordList={objects} title="object" color={magenta[7]} />
      </div>
    </>
  );
}
